### ISSUE TITLE
Parsing yml file

### ISSUE THREAD

**Issue by pierrepeterlongo** [kalininalab/metaprofi#1]
Hello, 

Thanks a lot for your work in Metaprofi.

I'm facing issues while parsing the yml file. 

here it is: 
```
h: <1>
k: <28>
m: <30000000000>
nproc: <32>
max_memory: <800GiB>
sequence_type: <nucleotide>
output_directory: <index_metaprofi_dir>
matrix_store_name: <metaprofi_bfmatrix>
index_store_name: <metaprofi_index>
```
(I've tried with ou without '<' '>' characters).

The output is 
```
Traceback (most recent call last):
  File "/home/symbiose/ppeterlo/.conda/envs/metaprofi/bin/metaprofi", line 8, in <module>
    sys.exit(main())
  File "/home/symbiose/ppeterlo/.conda/envs/metaprofi/lib/python3.8/site-packages/metaprofi/metaprofi_main.py", line 149, in main
    config = get_config(args.config_file, config_check=True)
  File "/home/symbiose/ppeterlo/.conda/envs/metaprofi/lib/python3.8/site-packages/metaprofi/lib/utilities.py", line 44, in get_config
    config = check_config(loaded_config)
  File "/home/symbiose/ppeterlo/.conda/envs/metaprofi/lib/python3.8/site-packages/metaprofi/lib/utilities.py", line 258, in check_config
    if config["m"] % 8 == 0:
TypeError: not all arguments converted during string formatting
```
(note that I tried several distinct `m` values (factor or 8 or not)

Am I doing something wrong?

Best, 
Pierre

**Comment by sanjaysrikakulam** [comment]
Hi Pierre,

Thank you for using MetaProFi!

I ran a test with your config file and it works perfectly fine. Here is the config I tried

```
h: 1
k: 28
m: 30000000000
nproc: 32
max_memory: 500GiB
sequence_type: nucleotide
output_directory: /test/sanjay/test_data/
matrix_store_name: metaprofi_bfmatrix
index_store_name: metaprofi_index
```

The config values should not include the angular (`<`, `>`) parentheses.

BTW `m` can be anything. 

This was my test setup:
1. Followed the installation setup as described in the [readme](https://github.com/kalininalab/metaprofi#installation)
2. Used the dataset from our [rna_seq_mini_index](https://github.com/kalininalab/metaprofi/tree/main/benchmarks/rna_seq_mini_index) benchmark with the above config as a `config.yml` file.

Hope this helps.

**Comment by pierrepeterlongo** [comment]
Indeed, it works now, after copy-pasting your config. 
I do not understand what was wrong. 


Anyway, thanks a lot for your time. 
Best, 
Pierre
